version: "3.9"
services:
  api:
    build: ./backend
    env_file: .env
    ports: ["3030:3000"]
    depends_on: [db]
    volumes: ["./backend:/app"]

  web:
    build: ./frontend
    ports: ["5173:5173"]
    volumes: ["./frontend:/app"]
    depends_on: [api]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports: ["3306:3306"]
    volumes: ["db-data:/var/lib/mysql"]

volumes:
  db-data:
